-- Execute este script no Oracle como usuário CONTA_APP

-- Dropar tabela se existir
DROP TABLE CONTA CASCADE CONSTRAINTS;
DROP SEQUENCE CONTA_SEQ;

-- Criar sequência
CREATE SEQUENCE CONTA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criar tabela CONTA
CREATE TABLE CONTA (
    ID NUMBER(19) NOT NULL,
    TITULAR VARCHAR2(100) NOT NULL,
    SALDO NUMBER(15,2) NOT NULL,
    CONSTRAINT PK_CONTA PRIMARY KEY (ID),
    CONSTRAINT CK_CONTA_SALDO CHECK (SALDO >= 0)
);

-- Inserir dados de teste
INSERT INTO CONTA (ID, TITULAR, SALDO) VALUES (CONTA_SEQ.NEXTVAL, 'João Silva', 1000.00);
INSERT INTO CONTA (ID, TITULAR, SALDO) VALUES (CONTA_SEQ.NEXTVAL, 'Maria Santos', 2500.50);
INSERT INTO CONTA (ID, TITULAR, SALDO) VALUES (CONTA_SEQ.NEXTVAL, 'Pedro Oliveira', 750.25);

COMMIT;

-- Verificar se foi criado corretamente
SELECT * FROM CONTA;
DESC CONTA;