-- ========================================
-- SCRIPT PARA POPULAR DADOS - EXECUTE APÓS REINICIAR SPRING BOOT
-- ========================================

-- Verificar se as tabelas foram recriadas pelo Spring
SELECT table_name FROM user_tables WHERE table_name IN ('CLIENTE', 'CONTA', 'MOVIMENTACAO');

-- Limpar dados existentes (se houver)
DELETE FROM MOVIMENTACAO;
DELETE FROM CONTA;
DELETE FROM CLIENTE;

-- Verificar se sequências existem e recriar se necessário
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOVIMENTACAO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Criar sequências
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOVIMENTACAO START WITH 1 INCREMENT BY 1;

-- Inserir 10 clientes
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'João Silva Santos', '12345678901', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Maria Oliveira Costa', '23456789012', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Pedro Almeida Lima', '34567890123', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Ana Carolina Souza', '45678901234', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Carlos Eduardo Pereira', '56789012345', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Fernanda Rodrigues', '67890123456', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Ricardo Mendes Silva', '78901234567', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Juliana Ferreira', '89012345678', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Roberto Carlos Dias', '90123456789', CURRENT_TIMESTAMP);
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) VALUES (SEQ_CLIENTE.NEXTVAL, 'Camila Santos Rocha', '01234567890', CURRENT_TIMESTAMP);

-- Inserir 10 contas (uma para cada cliente)
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 1, 1500.00);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 2, 2300.50);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 3, 850.75);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 4, 3200.00);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 5, 1750.25);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 6, 4100.80);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 7, 920.30);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 8, 2800.60);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 9, 1200.90);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 10, 3500.40);

-- Inserir movimentações (2 para cada conta)
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 1, 'DEPOSITO', 500.00, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 1, 'SAQUE', 200.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 2, 'DEPOSITO', 800.50, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 2, 'SAQUE', 300.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 3, 'DEPOSITO', 400.75, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 3, 'SAQUE', 150.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 4, 'DEPOSITO', 1200.00, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 4, 'SAQUE', 500.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 5, 'DEPOSITO', 750.25, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 5, 'SAQUE', 250.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 6, 'DEPOSITO', 1100.80, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 6, 'SAQUE', 400.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 7, 'DEPOSITO', 420.30, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 7, 'SAQUE', 180.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 8, 'DEPOSITO', 900.60, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 8, 'SAQUE', 350.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 9, 'DEPOSITO', 600.90, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 9, 'SAQUE', 220.00, CURRENT_TIMESTAMP);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 10, 'DEPOSITO', 1000.40, CURRENT_TIMESTAMP);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR, DATA_MOVIMENTACAO) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 10, 'SAQUE', 450.00, CURRENT_TIMESTAMP);

-- Confirmar dados
COMMIT;

-- Verificar resultados
SELECT COUNT(*) AS total_clientes FROM CLIENTE;
SELECT COUNT(*) AS total_contas FROM CONTA;
SELECT COUNT(*) AS total_movimentacoes FROM MOVIMENTACAO;

SELECT 'Dados populados com sucesso!' AS status FROM dual;