-- =====================================================
-- SCRIPT PARA POVOAR TABELAS NO ORACLE - CONTA_APP
-- Execute no DBeaver conectado como CONTA_APP/1234
-- =====================================================

-- Verificar dados existentes
SELECT 'CLIENTES EXISTENTES' AS INFO, COUNT(*) AS TOTAL FROM CLIENTE;
SELECT 'CONTAS EXISTENTES' AS INFO, COUNT(*) AS TOTAL FROM CONTA;
SELECT 'MOVIMENTACOES EXISTENTES' AS INFO, COUNT(*) AS TOTAL FROM MOVIMENTACAO;

-- Limpar dados existentes (respeitando foreign keys)
DELETE FROM MOVIMENTACAO;
DELETE FROM CONTA;
-- NÃO deletar CLIENTE pois já existe o registro ID=1

-- Verificar se existe cliente ID=1
SELECT * FROM CLIENTE WHERE ID_CLIENTE = 1;

-- =====================================================
-- INSERIR CLIENTES ADICIONAIS (mantendo o existente ID=1)
-- =====================================================
-- Inserir apenas se não existirem
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) 
SELECT 2, 'Maria Oliveira Costa', '98765432100', SYSDATE - 25 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE ID_CLIENTE = 2);

INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) 
SELECT 3, 'Pedro Henrique Lima', '11122233344', SYSDATE - 20 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE ID_CLIENTE = 3);

INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) 
SELECT 4, 'Ana Carolina Souza', '55566677788', SYSDATE - 15 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE ID_CLIENTE = 4);

INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF, DATA_CADASTRO) 
SELECT 5, 'Carlos Eduardo Rocha', '99988877766', SYSDATE - 10 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE ID_CLIENTE = 5);

-- =====================================================
-- POVOAR TABELA CONTA (5 registros)
-- =====================================================
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO, DATA_CRIACAO) VALUES 
(1, 1, 1500.00, SYSDATE - 30);

INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO, DATA_CRIACAO) VALUES 
(2, 2, 2750.50, SYSDATE - 25);

INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO, DATA_CRIACAO) VALUES 
(3, 3, 890.25, SYSDATE - 20);

INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO, DATA_CRIACAO) VALUES 
(4, 4, 3200.75, SYSDATE - 15);

INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO, DATA_CRIACAO) VALUES 
(5, 5, 450.00, SYSDATE - 10);

-- =====================================================
-- POVOAR TABELA MOVIMENTACAO (5 registros por conta = 25 total)
-- =====================================================

-- Movimentações da Conta 1 (Cliente Teste)
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(100, 1, 'DEPOSITO', 1000.00, SYSDATE - 30);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(101, 1, 'DEPOSITO', 800.00, SYSDATE - 28);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(102, 1, 'SAQUE', 200.00, SYSDATE - 25);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(103, 1, 'SAQUE', 100.00, SYSDATE - 20);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(104, 1, 'DEPOSITO', 500.00, SYSDATE - 15);

-- Movimentações da Conta 2 (Maria Oliveira)
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(200, 2, 'DEPOSITO', 2000.00, SYSDATE - 25);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(201, 2, 'DEPOSITO', 1000.00, SYSDATE - 22);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(202, 2, 'SAQUE', 150.50, SYSDATE - 18);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(203, 2, 'SAQUE', 99.00, SYSDATE - 12);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(204, 2, 'DEPOSITO', 250.00, SYSDATE - 8);

-- Movimentações da Conta 3 (Pedro Henrique)
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(300, 3, 'DEPOSITO', 500.00, SYSDATE - 20);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(301, 3, 'DEPOSITO', 600.00, SYSDATE - 18);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(302, 3, 'SAQUE', 75.25, SYSDATE - 15);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(303, 3, 'SAQUE', 134.50, SYSDATE - 10);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(304, 3, 'DEPOSITO', 300.00, SYSDATE - 5);

-- Movimentações da Conta 4 (Ana Carolina)
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(400, 4, 'DEPOSITO', 3000.00, SYSDATE - 15);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(401, 4, 'DEPOSITO', 500.00, SYSDATE - 12);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(402, 4, 'SAQUE', 200.25, SYSDATE - 8);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(403, 4, 'SAQUE', 99.00, SYSDATE - 5);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(404, 4, 'DEPOSITO', 1000.00, SYSDATE - 2);

-- Movimentações da Conta 5 (Carlos Eduardo)
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(500, 5, 'DEPOSITO', 400.00, SYSDATE - 10);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(501, 5, 'DEPOSITO', 200.00, SYSDATE - 8);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(502, 5, 'SAQUE', 50.00, SYSDATE - 6);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(503, 5, 'SAQUE', 100.00, SYSDATE - 3);
INSERT INTO MOVIMENTACAO (ID_MOV, ID_CONTA, TIPO, VALOR, DATA_MOV) VALUES 
(504, 5, 'DEPOSITO', 150.00, SYSDATE - 1);

-- Confirmar transações
COMMIT;

-- =====================================================
-- VERIFICAR DADOS INSERIDOS
-- =====================================================
SELECT 'CLIENTES' AS TABELA, COUNT(*) AS TOTAL FROM CLIENTE
UNION ALL
SELECT 'CONTAS' AS TABELA, COUNT(*) AS TOTAL FROM CONTA
UNION ALL
SELECT 'MOVIMENTACOES' AS TABELA, COUNT(*) AS TOTAL FROM MOVIMENTACAO;

-- Consulta completa com JOIN
SELECT 
    c.ID_CLIENTE,
    c.NOME AS CLIENTE_NOME,
    c.CPF,
    ct.ID_CONTA,
    ct.SALDO,
    ct.DATA_CRIACAO,
    COUNT(m.ID_MOV) AS TOTAL_MOVIMENTACOES
FROM CLIENTE c
JOIN CONTA ct ON c.ID_CLIENTE = ct.ID_CLIENTE
LEFT JOIN MOVIMENTACAO m ON ct.ID_CONTA = m.ID_CONTA
GROUP BY c.ID_CLIENTE, c.NOME, c.CPF, ct.ID_CONTA, ct.SALDO, ct.DATA_CRIACAO
ORDER BY c.ID_CLIENTE;

-- Verificar movimentações por conta
SELECT 
    ct.ID_CONTA,
    cl.NOME,
    m.TIPO,
    m.VALOR,
    m.DATA_MOV
FROM MOVIMENTACAO m
JOIN CONTA ct ON m.ID_CONTA = ct.ID_CONTA
JOIN CLIENTE cl ON ct.ID_CLIENTE = cl.ID_CLIENTE
ORDER BY ct.ID_CONTA, m.DATA_MOV DESC;