-- ========================================
-- MIGRATION V1: Criar estrutura das tabelas
-- ========================================

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela CONTA
CREATE TABLE CONTA (
    ID_CONTA NUMBER(10) PRIMARY KEY,
    ID_CLIENTE NUMBER(10) NOT NULL,
    SALDO NUMBER(15,2) DEFAULT 0.00,
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela MOVIMENTACAO
CREATE TABLE MOVIMENTACAO (
    ID_MOVIMENTACAO NUMBER(10) PRIMARY KEY,
    ID_CONTA NUMBER(10) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL CHECK (TIPO IN ('DEPOSITO', 'SAQUE')),
    VALOR NUMBER(15,2) NOT NULL,
    DATA_MOVIMENTACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MOVIMENTACAO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
);

-- Criar sequências
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOVIMENTACAO START WITH 1 INCREMENT BY 1;