-- ========================================
-- MIGRATION V1: Criar tabelas e popular dados
-- ========================================

-- 1. CRIAR TABELAS
-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela CONTA
CREATE TABLE CONTA (
    ID_CONTA NUMBER(10) PRIMARY KEY,
    ID_CLIENTE NUMBER(10) NOT NULL,
    SALDO NUMBER(15,2) DEFAULT 0.00,
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela MOVIMENTACAO
CREATE TABLE MOVIMENTACAO (
    ID_MOVIMENTACAO NUMBER(10) PRIMARY KEY,
    ID_CONTA NUMBER(10) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL CHECK (TIPO IN ('DEPOSITO', 'SAQUE')),
    VALOR NUMBER(15,2) NOT NULL,
    DATA_MOVIMENTACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MOVIMENTACAO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
);

-- 2. CRIAR SEQUÊNCIAS
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOVIMENTACAO START WITH 1 INCREMENT BY 1;

-- 3. POPULAR COM DADOS DE TESTE
-- Inserir 10 clientes
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'João Silva Santos', '12345678901');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Maria Oliveira Costa', '23456789012');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Pedro Almeida Lima', '34567890123');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Ana Carolina Souza', '45678901234');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Carlos Eduardo Pereira', '56789012345');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Fernanda Rodrigues', '67890123456');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Ricardo Mendes Silva', '78901234567');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Juliana Ferreira', '89012345678');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Roberto Carlos Dias', '90123456789');
INSERT INTO CLIENTE (ID_CLIENTE, NOME, CPF) VALUES (SEQ_CLIENTE.NEXTVAL, 'Camila Santos Rocha', '01234567890');

-- Inserir 10 contas (uma para cada cliente)
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 1, 1500.00);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 2, 2300.50);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 3, 850.75);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 4, 3200.00);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 5, 1750.25);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 6, 4100.80);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 7, 920.30);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 8, 2800.60);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 9, 1200.90);
INSERT INTO CONTA (ID_CONTA, ID_CLIENTE, SALDO) VALUES (SEQ_CONTA.NEXTVAL, 10, 3500.40);

-- Inserir movimentações (2 para cada conta: 1 depósito + 1 saque)
-- Conta 1
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 1, 'DEPOSITO', 500.00);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 1, 'SAQUE', 200.00);

-- Conta 2
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 2, 'DEPOSITO', 800.50);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 2, 'SAQUE', 300.00);

-- Conta 3
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 3, 'DEPOSITO', 400.75);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 3, 'SAQUE', 150.00);

-- Conta 4
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 4, 'DEPOSITO', 1200.00);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 4, 'SAQUE', 500.00);

-- Conta 5
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 5, 'DEPOSITO', 750.25);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 5, 'SAQUE', 250.00);

-- Conta 6
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 6, 'DEPOSITO', 1100.80);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 6, 'SAQUE', 400.00);

-- Conta 7
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 7, 'DEPOSITO', 420.30);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 7, 'SAQUE', 180.00);

-- Conta 8
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 8, 'DEPOSITO', 900.60);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 8, 'SAQUE', 350.00);

-- Conta 9
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 9, 'DEPOSITO', 600.90);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 9, 'SAQUE', 220.00);

-- Conta 10
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 10, 'DEPOSITO', 1000.40);
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, ID_CONTA, TIPO, VALOR) VALUES (SEQ_MOVIMENTACAO.NEXTVAL, 10, 'SAQUE', 450.00);