-- =====================================================
-- Migration V3: Criação da tabela de usuários
-- =====================================================
-- Esta migration cria a tabela usuarios para armazenar
-- credenciais de acesso ao sistema com autenticação JWT

-- Criação da tabela usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID auto-incremento
    login VARCHAR2(100) NOT NULL UNIQUE,                     -- Login único do usuário
    senha VARCHAR2(255) NOT NULL                             -- Senha criptografada com BCrypt
);

-- Comentários para documentação da tabela
COMMENT ON TABLE usuarios IS 'Tabela de usuários do sistema para autenticação JWT';
COMMENT ON COLUMN usuarios.id IS 'Identificador único do usuário (chave primária)';
COMMENT ON COLUMN usuarios.login IS 'Nome de usuário para login (deve ser único)';
COMMENT ON COLUMN usuarios.senha IS 'Senha criptografada com algoritmo BCrypt';

-- Índice para otimizar consultas por login
CREATE INDEX idx_usuarios_login ON usuarios(login);